apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: droneenergysim-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: droneenergysim-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
