apiVersion: apps/v1
kind: Deployment
metadata:
  name: droneenergysim-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: droneenergysim
  template:
    metadata:
      labels:
        app: droneenergysim
    spec:
      containers:
      - name: droneenergysim
        image: droneenergysim:latest
