apiVersion: apps/v1
kind: Deployment
metadata:
  name: zmqpublisher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zmqpublisher
  template:
    metadata:
      labels:
        app: zmqpublisher
    spec:
      containers:
      - name: zmqpublisher
        image: zmqpublisher:latest
